spring:
  application:
    name: Food Quiz
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: changeit
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      platform: dev
