FOODS = [
    {"name": "Riz blanc cuit", "query": "riz blanc cuit", "portion_g": 180},
    {"name": "Pâtes cuites", "query": "pâtes cuites", "portion_g": 200},
    {"name": "Pain de mie blanc", "query": "pain de mie blanc", "portion_g": 60},
    {"name": "Baguette", "query": "baguette pain", "portion_g": 80},
    {"name": "Pomme de terre cuite", "query": "pomme de terre cuite vapeur", "portion_g": 200},
    {"name": "Frites", "query": "frites", "portion_g": 150},
    {"name": "Lentilles cuites", "query": "lentilles vertes cuites", "portion_g": 180},
    {"name": "Pois chiches cuits", "query": "pois chiches cuits", "portion_g": 180},
    {"name": "Haricots rouges cuits", "query": "haricots rouges cuits", "portion_g": 180},
    {"name": "Flocons d'avoine", "query": "flocons avoine", "portion_g": 50},
    {"name": "Corn flakes", "query": "corn flakes céréales", "portion_g": 40},
    {"name": "Muesli", "query": "muesli céréales", "portion_g": 50},
    {"name": "Banane", "query": "banane fruit", "portion_g": 120},
    {"name": "Raisin", "query": "raisin fruit", "portion_g": 100},
    {"name": "Jus d'orange", "query": "jus orange", "portion_g": 200},
    {"name": "Jus de pomme", "query": "jus pomme", "portion_g": 200},
    {"name": "Pomme", "query": "pomme fruit", "portion_g": 150},
    {"name": "Orange", "query": "orange fruit", "portion_g": 150},
    {"name": "Mangue", "query": "mangue fruit", "portion_g": 150},
    {"name": "Pizza margherita", "query": "pizza margherita", "portion_g": 200},
    {"name": "Crêpe sucrée", "query": "crêpe sucrée", "portion_g": 80},
    {"name": "Gaufre", "query": "gaufre", "portion_g": 80},
    {"name": "Croissant", "query": "croissant", "portion_g": 60},
    {"name": "Pain au chocolat", "query": "pain au chocolat", "portion_g": 70},
    {"name": "Yaourt sucré", "query": "yaourt sucré aux fruits", "portion_g": 125},
    {"name": "Lait entier", "query": "lait entier", "portion_g": 250},
    {"name": "Soda cola", "query": "coca-cola soda", "portion_g": 330},
    {"name": "Biscuits secs", "query": "biscuits petit beurre", "portion_g": 40},
    {"name": "Chocolat au lait", "query": "chocolat au lait", "portion_g": 30},
    {"name": "Miel", "query": "miel", "portion_g": 20},
    {"name": "Confiture", "query": "confiture fraise", "portion_g": 30},
    {"name": "Semoule cuite", "query": "semoule cuite couscous", "portion_g": 180},
    {"name": "Quinoa cuit", "query": "quinoa cuit", "portion_g": 180},
    {"name": "Boulgour cuit", "query": "boulgour cuit", "portion_g": 180},
    {"name": "Maïs en grains", "query": "maïs grains", "portion_g": 150},
    {"name": "Petits pois cuits", "query": "petits pois cuits", "portion_g": 150},
    {"name": "Betterave cuite", "query": "betterave cuite", "portion_g": 150},
    {"name": "Carottes cuites", "query": "carottes cuites", "portion_g": 150},
    {"name": "Patate douce cuite", "query": "patate douce cuite", "portion_g": 150},
    {"name": "Tarte aux pommes", "query": "tarte pomme", "portion_g": 100},
    {"name": "Brownie chocolat", "query": "brownie chocolat", "portion_g": 80},
    {"name": "Muffin", "query": "muffin", "portion_g": 90},
    {"name": "Galette de riz", "query": "galette riz soufflée", "portion_g": 30},
    {"name": "Riz au lait", "query": "riz au lait dessert", "portion_g": 150},
    {"name": "Sorbet citron", "query": "sorbet citron", "portion_g": 100},
    {"name": "Glace vanille", "query": "glace vanille", "portion_g": 100},
    {"name": "Cake nature", "query": "cake nature", "portion_g": 80},
    {"name": "Pancakes", "query": "pancakes", "portion_g": 120},
    {"name": "Brioche", "query": "brioche", "portion_g": 60},
    {"name": "Wrap farine", "query": "wrap farine blé", "portion_g": 60},
]
